In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [4]:
diabet = pd.read_csv('diabetes.csv')
diabet.head(10)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1
5            5      116             74  ...                     0.201   30        0
6            3       78             50  ...                     0.248   26        1
7           10      115              0  ...                     0.134   29        0
8            2      197             70  ...                     0.158   53        1
9            8      125             96  ...                     0.232   54        1

[10 rows x 9 columns]

In [5]:
diabet = diabet.drop(['Outcome'], axis = 1)
diabet.head(10)

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33
5            5      116             74  ...  25.6                     0.201   30
6            3       78             50  ...  31.0                     0.248   26
7           10      115              0  ...  35.3                     0.134   29
8            2      197             70  ...  30.5                     0.158   53
9            8      125             96  ...   0.0                     0.232   54

[10 rows x 8 columns]

In [7]:
print ("Shape of dataset before cleaning: ", diabet.size)
diabet[[ 'Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']] = diabet[['Pregnancies','Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']].apply(pd.to_numeric, errors='coerce')
diabet = diabet.dropna()
diabet = diabet.reset_index(drop=True)
print ("Shape of dataset after cleaning: ", diabet.size)
diabet.head(10)

Shape of dataset before cleaning:  6144
Shape of dataset after cleaning:  6144


Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33
5            5      116             74  ...  25.6                     0.201   30
6            3       78             50  ...  31.0                     0.248   26
7           10      115              0  ...  35.3                     0.134   29
8            2      197             70  ...  30.5                     0.158   53
9            8      125             96  ...   0.0                     0.232   54

[10 rows x 8 columns]

In [11]:
diabet_x = diabet.iloc[:, :8]
diabet_x.head(10)

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33
5            5      116             74  ...  25.6                     0.201   30
6            3       78             50  ...  31.0                     0.248   26
7           10      115              0  ...  35.3                     0.134   29
8            2      197             70  ...  30.5                     0.158   53
9            8      125             96  ...   0.0                     0.232   54

[10 rows x 8 columns]

In [13]:
x_array =  np.array(diabet_x)
print(x_array)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [14]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_array)
x_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [15]:
kmeans = KMeans(init = "k-means++", n_clusters = 4, random_state=200)
kmeans.fit(x_scaled)
center = kmeans.cluster_centers_
center

array([[ 1.03076633,  0.25293989,  0.4515361 , -0.4754104 , -0.45067054,
        -0.00660133, -0.11142779,  1.08524303],
       [-0.50993451, -0.56195833, -0.04798291, -0.05699167, -0.24357595,
        -0.27887068, -0.18178172, -0.61388454],
       [-0.2273298 ,  0.81862707,  0.27359786,  0.92188271,  1.15942767,
         0.71471851,  0.53814346, -0.0586892 ],
       [-0.08597076, -0.12188771, -3.53813207, -1.16275609, -0.68686078,
        -0.79054054, -0.23771244, -0.23794288]])

In [18]:
kmeans.labels_

array([0, 1, 0, 1, 2, 1, 1, 3, 2, 0, 1, 0, 0, 2, 0, 3, 2, 0, 1, 1, 2, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 2, 2, 0, 0, 2,
       0, 2, 1, 1, 1, 3, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 3, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 3, 1, 1, 3, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 2, 1, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 2, 0,
       2, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 2, 1, 0, 2, 0, 1, 2, 1, 2, 2,
       0, 2, 1, 1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 2, 3, 1, 1, 2,
       0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 2, 2, 1, 2, 1, 0, 0, 3, 0, 2, 1, 1,
       2, 2, 1, 1, 1, 1, 0, 1, 2, 0, 1, 0, 1, 2, 0, 2, 0, 2, 2, 1, 1, 0,
       2, 0, 3, 0, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1,
       1, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 2, 3, 1, 0,
       1, 0, 3, 2, 1, 3, 0, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       2, 2, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 3,

In [19]:
diabet["Cluster"] = kmeans.labels_
diabet.head(10)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Cluster
0            6      148             72  ...                     0.627   50        0
1            1       85             66  ...                     0.351   31        1
2            8      183             64  ...                     0.672   32        0
3            1       89             66  ...                     0.167   21        1
4            0      137             40  ...                     2.288   33        2
5            5      116             74  ...                     0.201   30        1
6            3       78             50  ...                     0.248   26        1
7           10      115              0  ...                     0.134   29        3
8            2      197             70  ...                     0.158   53        2
9            8      125             96  ...                     0.232   54        0

[10 rows x 9 columns]